on:
  workflow_dispatch:
    inputs:
      image_reference:
        description: 'Docker Image (andrefgpinho/go-fibonacci-api:589f021)'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest      
    environment:
      name: production
      url: https://devops-server.intro.codeforall.io
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.EC2_PASSWORD }}
          script: |
            docker pull ${{ github.event.inputs.image_reference }}
            docker stop fibonacci || true
            docker rm fibonacci || true
            docker run -d --name fibonacci -p 8083:8080 ${{ github.event.inputs.image_reference }}

